export const PathName = {
  Login: '/',
  Dashboard: '/dashboard',
  ForgotPassword: '/forgot-password',
  ResetPassword: '/reset-password',
  Events: '/events',
  Places: '/places',
  Organizations: '/organizations',
  People: '/people',
  Taxonomies: '/taxonomies',
  Settings: '/settings',
  AddEvent: '/add-event',
  AcceptInvitation: '/accept',
  Join: '/join',
  User: '/user',
  Profile: '/profile',
  NotFound: '/*',
};
