export const organizationFormFieldNames = {
  NAME: 'NAME',
  DISAMBIGUATING_DESCRIPTION: 'DISAMBIGUATING_DESCRIPTION',
  DESCRIPTION: 'DESCRIPTION',
  WEBSITE: 'URL',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA_LINKS',
  LOGO: 'LOGO',
  IMAGE: 'IMAGE',
  LOCATION: 'PLACE',
  CONTACT_TITLE: 'CONTACT_POINT_NAME',
  CONTACT_WEBSITE: 'CONTACT_POINT_WEBSITE',
  PHONE_NUMBER: 'CONTACT_POINT_TELEPHONE',
  EMAIL: 'CONTACT_POINT_EMAIL',
  ORGANIZATION_TYPE: 'ADDITIONAL_TYPE',
};

export const personFormFieldNames = {
  NAME: 'NAME',
  DISAMBIGUATING_DESCRIPTION: 'DISAMBIGUATING_DESCRIPTION',
  DESCRIPTION: 'DESCRIPTION',
  WEBSITE: 'URL',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA_LINKS',
  IMAGE: 'IMAGE',
  OCCUPATION: 'OCCUPATION',
};
