name: Staging build and deploy to S3
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  build-and-preview:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1 
      WEBHOSTING_BUCKET_NAME: staging.cms.footlight.io
    runs-on: ubuntu-latest
    container:
      image: sleavely/node-awscli:14.x
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        run: npm install

      - name: Build
        run: npm run build:staging
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Create Preview Bucket
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          TIMESTAMP=$(date +%s)
          PREVIEW_BUCKET="preview-bucket-${PR_NUMBER}-${TIMESTAMP}"
          REGION=$(aws configure get region)
          echo "Creating bucket $PREVIEW_BUCKET in region $REGION"
          if ! aws s3 mb s3://$PREVIEW_BUCKET --region $REGION 2>&1; then
            echo "Error creating bucket!"
          fi
          echo "Preview bucket created: ${PREVIEW_BUCKET}"

      - name: Deploy to S3
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          PREVIEW_BUCKET="preview-bucket-${PR_NUMBER}"
          aws s3 sync ./build s3://${PREVIEW_BUCKET}
          echo "Preview deployed to ${PREVIEW_BUCKET}"
