name: Staging build and deploy to S3

on:
  push:
    branches:
      - develop

  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened

jobs:
 build-and-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build for Preview
        run: npm run build

      - name: Deploy to Preview Channel
        run: |
          BUCKET_NAME="preview-channel-${GITHUB_RUN_ID}"
          aws s3 sync .build/ "s3://${BUCKET_NAME}/"

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
