name: Production build and deploy to S3
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: sleavely/node-awscli:14.x
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build:production
    - run: aws s3 sync ./build s3://cms.footlight.io/ --acl public-read --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1 
        WEBHOSTING_BUCKET_NAME: cms.footlight.io
                
    # Invalidate CloudFront (this action)
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/index.html"
        AWS_REGION: "ca-central-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
