name: Production build and deploy to S3
on:
  push:
    branches:
      - main
jobs:
  trigger-cypress-tests:
    uses: ./.github/workflows/run-cypress-tests.yml
    with:
      environment: 'production'
      grep: ''
      grepTags: '@essential'
    secrets:
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      STAGING_SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
      AWS_PRIVATE_KEY_UBUNTU_USER: ${{ secrets.AWS_PRIVATE_KEY_UBUNTU_USER }}

  build-and-deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1 
      WEBHOSTING_BUCKET_NAME: cms.footlight.io
    runs-on: ubuntu-latest
    container:
      image: sleavely/node-awscli:14.x
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: setup node
        run: npm install

      # Append additional environment variables to .env.staging
      - name: Add extra env variables
        run: |
          echo "" >> .env.production
          echo "REACT_APP_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env.production
          echo "REACT_APP_GOOGLE_MAPS_ID=${{ secrets.GOOGLE_MAPS_ID }}" >> .env.production  
        
      - name: build
        run: npm run build:production
        
      # Upload to S3
      - name: sync s3
        run: aws s3 sync ./build s3://${{env.WEBHOSTING_BUCKET_NAME}}/ --acl public-read --delete --exclude index.html

      - name: set cache-control on index.html 
        run: aws s3 cp ./build/index.html s3://${{env.WEBHOSTING_BUCKET_NAME}}/index.html --metadata-directive REPLACE --cache-control max-age=0,s-maxage=86400 --acl public-read --content-type text/html

      # Invalidate CloudFront (this action)
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E3S97I9K4Q2UXB
          PATHS: "/*"

  release-notification:
    if: success()
    name: Send Email on Success
    needs: build-and-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        to-emails:
          - ${{ vars.SENDGRID_TO_EMAIL }}
          - ${{ vars.SUPPORT_EMAIL}}

    steps:
      - uses: licenseware/send-email-notification@v1

        with:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          subject: Footlight CMS Deployment
          from-email: ${{ vars.SENDGRID_FROM_EMAIL }}
          to-email: ${{ matrix.to-emails }}
          markdown-body: ${{vars.NEW_RELEASE_MARKDOWN_PAGE}}