name: Deploy Preview

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  build-and-preview:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build:staging
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Create Preview Bucket
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          PREVIEW_BUCKET="your-preview-bucket-${PR_NUMBER}"
          aws s3api create-bucket --bucket $PREVIEW_BUCKET
          echo "Preview bucket created: ${PREVIEW_BUCKET}"

      - name: Deploy to S3
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          PREVIEW_BUCKET="your-preview-bucket-${PR_NUMBER}"
          aws s3 sync ./build s3://${PREVIEW_BUCKET}
          echo "Preview deployed to ${PREVIEW_BUCKET}"
