name: PR

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        run: npm install
      - name: build
        run: npm run build:staging

      - name: Deploy S3 Website
        uses: danburtenshaw/s3-website-pr-action@v2
        with:
          bucket-prefix: "preview.cms.footlight.io"
          folder-to-copy: "./build"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_REGION: ca-central-1 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
