name: Build and Deploy React App on PR

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1
      WEBHOSTING_BUCKET_NAME: preview.cms.footlight.io

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Preview Channel
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            aws s3 sync ./build s3://preview.cms.footlight.io/${{ github.event.number }}/ --acl public-read --delete
            PR_PREVIEW_URL="https://preview.cms.footlight.io.s3.amazonaws.com/${{ github.event.number }}/index.html"
            echo "Preview URL: $PR_PREVIEW_URL"

            # Set deployment status
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/deployments/${{ github.run_id }}/statuses" \
              -d "{\"state\": \"success\", \"target_url\": \"$PR_PREVIEW_URL\", \"description\": \"Preview URL\"}"
          else
            echo "Not a pull request. Skipping deployment."
          fi
