name: Build the production Docker image for the footlight-app.

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/footlight-app
 
jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_URL: http://localhost:3001/
          envkey_REACT_APP_ARTS_DATA_URI: https://api.artsdata.ca/
          envkey_REACT_APP_ARTS_DATA_PAGE_URI: https://kg.artsdata.ca/resource/
          envkey_REACT_APP_DEEPL_URL: https://www.deepl.com/translator#
          envkey_REACT_APP_HELP_EN_URL: https://footlight.gitbook.io/footlight-cms-guide
          envkey_REACT_APP_HELP_FR_URL: https://footlight.gitbook.io/guide-footlight-cms
          envkey_REACT_APP_FEATURE_FLAG_QUICK_CREATE_ORGANIZATION: true
          envkey_REACT_APP_FEATURE_FLAG_ORG_PERSON_PLACE_VIEW: true
          envkey_REACT_APP_FEATURE_FLAG_QUICK_CREATE_PEOPLE_PLACE: true
          envkey_REACT_APP_FEATURE_FLAG_EDIT_SCREEN_PEOPLE_PLACE_ORGANIZATION: true
          envkey_REACT_APP_FEATURE_FLAG_USERS: true
          envkey_REACT_APP_FEATURE_FLAG_TAXONOMY: true
          envkey_REACT_APP_FEATURE_FLAG_IMAGE_CROP: true
          envkey_REACT_APP_ENV: staging
          envkey_REACT_APP_INVITE_URL: http://localhost:3001/join?invitationId=
          envkey_REACT_APP_ACCEPT_URL: http://localhost:3001/accept?invitationId=
          envkey_REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          envkey_REACT_APP_GOOGLE_MAPS_ID: ${{ secrets.GOOGLE_MAPS_ID }}
          file_name: .env
          fail_on_empty: false

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}