name: Deploy to S3
on:
  push:
    branches:
    - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jeanlescure/react-deploy-to-s3-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        NODE_ENV: staging # optional: defaults to production
        AWS_S3_BUCKET: staging.cms.footlight.io
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1 # optional: defaults to us-east-1
        SOURCE_DIR: build # optional: defaults to public