name: Run regression tests on pull request to Develop

on:
    pull_request:
        branches:
          - develop

jobs:
  trigger-cypress-tests:
      uses: ./.github/workflows/run-cypress-tests.yml
      with:
        environment: 'staging'
        grep: ''
        grepTags: '@general'
      secrets:
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}